config/routes.rb
Rails.application.routes.draw do

  root "pages#home"

  resources :apps
  resources :articles 
  resources :books

  devise_for :users,  :path => '', 
                      :path_names => { :sign_in => "login", 
                                        :sign_out => "logout", 
                                        :sign_up => "register", 
                                        :account_update => "account-settings" }

  match '*path' => redirect('/'), via: :all if Rails.env.production?  

end

app/models/book.rb
# == Schema Information
#
# Table name: books
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  author     :string(255)
#  url        :string(255)
#  review     :text
#  created_at :datetime
#  updated_at :datetime
#  published  :boolean          default(FALSE)
#  category   :string(255)
#  image_path :string(255)
#

class Book < ActiveRecord::Base

  scope :by_newest,   -> { order("created_at DESC") }
  scope :unpublished, -> { where("published = False") }
  scope :published,   -> { where("published = True") } 

# Callback definitions.


# Scope definitions.

  def self.by_category(category)
    where(category: category)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  
  before_action :authorize_admin


  # GET /books
  # GET /books.json
  def index
    @books = Book.all
    @programming_books = Book.by_category("programming")
    @business_books    = Book.by_category("business")
    @science_books     = Book.by_category("science")
    @philosophy_books  = Book.by_category("philosophy")
    @to_read_books     = Book.by_category("to read")
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to books_path, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to books_path, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:category, :title, :author, :url, :image_path, :review, :published)
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_books.html.slim
/- require 'image_size'
/= ImageSize.path("http://localhost:3000/assets/github.png").size

/h1.media-heading.text-center 
/  | My Favorite Reads

- if currently_admin?
  .row
    .col-xs-12
      .admin
        = link_to 'Manage Books', books_path

.row
  .col-xs-12
    #bookshelf_slider.bookshelf_slider
      .panel_title
        .selected_title_box
          .selected_title
            | Selected Title
        .menu_top
          ul
            li.show_hide_titles.menutop_btn
              = link_to "#" do
                | Titles
            li.show_hide_icons.menutop_btn
              = link_to "#" do 
                | Icons

      .panel_slider
        .panel_items

          .slide_animate
            #products_box_1.products_box
              - @programming_books.each do |book|
                - if book.published || currently_admin?
                  /- fi = FastImage.size(asset_url("book/#{book.image_path}"))
                  /- fi_width = fi[0]
                  /- fi_height = fi[1]
                  = content_tag(:div, class: "product", title: "#{book.title}", data: { popup: "false", type: "book", url: "#{book.url}" }) do
                    = image_tag "books/#{book.image_path}", class: ["book", ("unpublished" if !book.published?)], alt: "#{book.title}", height: 120, width: 80
                  /, width: fi_width, height: fi_height

          .slide_animate
            #products_box_2.products_box
              - @business_books.each do |book|
                - if book.published || currently_admin?
                  = content_tag(:div, class: "product", title: "#{book.title}", data: { popup: "false", type: "book", url: "#{book.url}" }) do
                    = image_tag "books/#{book.image_path}", class: ["book", ("unpublished" if !book.published?)], alt: "#{book.title}", height: 120, width: 80

          .slide_animate
            #products_box_3.products_box
              - @science_books.each do |book|
                - if book.published || currently_admin?
                  = content_tag(:div, class: "product", title: "#{book.title}", data: { popup: "false", type: "book", url: "#{book.url}" }) do
                    = image_tag "books/#{book.image_path}", class: ["book", ("unpublished" if !book.published?)], alt: "#{book.title}", height: 120, width: 80

          .slide_animate
            #products_box_4.products_box
              - @philosophy_books.each do |book|
                - if book.published || currently_admin?
                  = content_tag(:div, class: "product", title: "#{book.title}", data: { popup: "false", type: "book", url: "#{book.url}" }) do
                    = image_tag "books/#{book.image_path}", class: ["book", ("unpublished" if !book.published?)], alt: "#{book.title}", height: 120, width: 80

          /.slide_animate
            #products_box_5.products_box
              - @to_read_books.each do |book|
                - if book.published || currently_admin?
                  = content_tag(:div, class: "product", title: "#{book.title}", data: { popup: "false", type: "book", url: "#{book.url}" }) do
                    = image_tag "books/#{book.image_path}", class: ["book", ("unpublished" if !book.published?)], alt: "#{book.title}", height: 120, width: 80

      .panel_bar
        .buttons-container
          #arrow_box
            #arrow_menu
          .button_items
            #btn1.button_bar
              = link_to "#" do
                | Programming
            #btn2.button_bar
              = link_to "#" do
                | Business
            #btn3.button_bar
              = link_to "#" do
                | Science
            #btn4.button_bar
              = link_to "#" do
                | Philosophy
            /#btn5.button_bar
              = link_to "#" do
                | To Read

app/views/books/_form.html.slim
= simple_form_for(@book) do |f|
  = f.error_notification

  .form-inputs
    = f.input :category

  .form-inputs
    = f.input :title

  .form-inputs
    = f.input :author

  .form-inputs
    = f.input :image_path

  .form-inputs
    = f.input :url

  .form-inputs
    = f.input :review

  .form-inputs
    = f.input :published, as: :boolean, label: false, inline_label: true

  .form-actions
    = f.button :submit

app/views/books/edit.html.slim
h1 Editing book

== render 'form'

- if currently_admin?
  = link_to 'Show', @book
  '|
  = link_to 'Back', books_path

app/views/books/index.html.slim
.container-fluid#bookshelf
  /- require 'image_size'
  /= ImageSize.path("http://localhost:3000/assets/github.png").size

  .row
    .col-xs-12

      - if currently_admin?
        = link_to 'New Book', new_book_path

  == render partial: "books/books", locals: { books: @books, 
                                              programming_books: @programming_books,
                                              business_books:    @business_books,
                                              science_books:     @science_books,  
                                              philosophy_books:  @philosophy_books,
                                              to_read_books:     @to_read_books }

  .row
    .col-xs-12
      #book_review
        /currently selected book.description

      - if currently_admin?
        table
          thead
            tr
              th Edit
              th Destroy
              th Published?
              th Category
              th Title
              th Author            
              th Description/Review/Notes

          tbody
            - @books.each do |book|
              tr
                td = link_to 'Edit', edit_book_path(book)
                td = link_to 'Destroy', book, data: {:confirm => 'Are you sure?'}, :method => :delete
                td = book.published
                td = book.category
                td = link_to book.title, book
                td = book.author              
                td = book.review
                

app/views/books/new.html.slim
h1 New book

== render 'form'

- if currently_admin?
  = link_to 'Back', books_path

app/views/books/show.html.slim
.row
  .col-xs-12
    h1.media-heading = @book.title

    - if currently_admin?
      = link_to 'Edit', edit_book_path(@book)
      '|
      = link_to 'Back', books_path

    = @book.author
    = @book.category

    = @book.image_path
    = @book.url

    = @book.review
    - if @book.published?
      | published