config/routes.rb
Rails.application.routes.draw do

  root "pages#home"

  resources :apps
  resources :articles 
  resources :books

  devise_for :users,  :path => '', 
                      :path_names => { :sign_in => "login", 
                                        :sign_out => "logout", 
                                        :sign_up => "register", 
                                        :account_update => "account-settings" }

  match '*path' => redirect('/'), via: :all if Rails.env.production?  

end

app/views/apps/_apps.html.slim
/ == render partial: "apps/apps", locals: { apps: @apps }

- if currently_admin?
  .row
    .col-xs-12
      .admin
        = link_to 'Manage Apps', apps_path

- unless apps.blank?
  .row
    - apps.each do |app|
      - if app.published? || currently_admin?
        .col-xs-6.col-md-4
          a[ href="" class="app-link" class=("unpublished" if !app.published?) data-toggle="modal" data-target=("##{app.name.parameterize}") ]  
            .app
              .app-name
                span = app.name.upcase
              .app-image
                = image_tag "apps/#{app.image_path}"

          div[ id=("#{app.name.parameterize}") class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" ]
            .modal-dialog.modal-lg
              .modal-content
                
                .modal-header.text-center 
                  .container-fluid
                    .row
                      .col-md-3.text-left
                        a.modal-exit
                          .glyphicon.glyphicon-chevron-left
                          | Back
                      .col-md-6
                        = app.name.titleize
                      .col-md-3.text-right
                        = link_to app.url, :target => "_blank" do 
                          | Check it out
                          .glyphicon.glyphicon-new-window
                .modal-body
                  .container-fluid
                    .row
                      .col-xs-12.col-md-8.col-md-push-4
                        = image_tag("apps/#{app.image_path}", class: "modal-app-image")
                      .col-xs-12.col-md-4.col-md-pull-8
                        = app.description.html_safe
                .modal-footer
                  .container-fluid
                    .row
                      - if currently_admin?
                        = link_to 'Edit', edit_app_path(app)
                        '  |
                        = link_to 'Destroy', app, data: {:confirm => 'Are you sure?'}, :method => :delete

app/views/apps/_form.html.slim
= simple_form_for(@app) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    
  .form-inputs
    = f.input :url, label: "URL (with protocol)"
    
  .form-inputs
    = f.input :image_path, label: "Local image filename (with extension)"

  .form-inputs
    = f.input :description

  .form-inputs
    = f.input :position

  .form-inputs
    = f.input :published, as: :boolean, label: false, inline_label: true

  .form-actions
    = f.button :submit, class: "btn-primary"

app/views/apps/edit.html.slim
.container-fluid
  .row
    .col-xs-12
      h1 Editing app

      == render 'form'

      = link_to 'Show', @app
      '  |
      = link_to 'Back', apps_path

app/views/apps/index.html.slim
.container-fluid#works
  .row
    .col-xs-12

      -if currently_admin?
        = link_to 'New App', new_app_path

  == render partial: "apps/apps", locals: { apps: @apps }

  -if currently_admin?
    .row
      .col-xs-12
      
        - @apps.each do |app|
          = app.name
          = app.position

app/views/apps/new.html.slim
h1 New app

== render 'form'

- if currently_admin?
  = link_to 'Back', apps_path

app/views/apps/show.html.slim
p
  strong Url:
  = @app.url

= link_to 'Edit', edit_app_path(@app)
'  |
= link_to 'Back', apps_path