config/routes.rb
Rails.application.routes.draw do

  root "pages#home"

  resources :apps
  resources :articles 
  resources :books

  devise_for :users,  :path => '', 
                      :path_names => { :sign_in => "login", 
                                        :sign_out => "logout", 
                                        :sign_up => "register", 
                                        :account_update => "account-settings" }

  match '*path' => redirect('/'), via: :all if Rails.env.production?  

end

app/views/layouts/_footer.html.slim
footer

  nav#footer-navbar.navbar-default

    ul.nav
      li
        = link_to "https://www.linkedin.com/in/jeehooahn", target: "_blank"  do
          = image_tag "social_icons/linkedin.png"
      li
        = link_to "https://github.com/ahnbizcad/", target: "_blank" do
          = image_tag "social_icons/github.png"
      li#email[ data-toggle="tooltip" data-placement="top", title="ahnjeehoo@gmail.com" ]
        = link_to "mailto:ahnjeehoo@gmail.com", target: "_blank" do
          = image_tag "social_icons/email.svg"

app/views/layouts/_header.html.slim
header
  .container-fluid

app/views/layouts/_navbar.html.slim
.affixable-wrapper
  nav#navbar.navbar.navbar-default.affixable[ role="navigation" ]

    ul#social-icons.nav.navbar-right
      li= link_to "https://github.com/ahnbizcad/" do
        = image_tag "github.png"
      li= link_to "https://www.linkedin.com/in/jeehooahn" do
        = image_tag "linkedin.png"

    ul#clause.nav.nav-tabs[ role="tablist" ]
      li.disabled= link_to "" do
        | "Gee, who
      li.dropdown.active
        = link_to "", class: "dropdown-toggle", data: { toggle: "dropdown" } do
          = @current_verb
          span.caret
        ul#verb.dropdown-menu[ role="menu"]
          li
            = link_to apps_path do
              .verb
                = @verbs["apps"] + " (apps)"
                '
              .label.label-primary
                = @published_apps_count
              - if currently_admin?
                .label.label-default[ data-toggle="tooltip" data-placement="right" title="Constructing" ]
                  = @unpublished_apps_count
              .clear-both
          li
            = link_to articles_path do
              .verb
                = @verbs["articles"] + " (blog)"
                '
              .label.label-primary
                = @published_articles_count
              - if currently_admin?
                .label.label-default[ data-toggle="tooltip" data-placement="right" title="In the works" ]
                  = @unpublished_articles_count
              .clear-both
          li
            = link_to books_path do
              .verb
                = @verbs["books"] + " (books)"
                '
              .label.label-primary
                = @published_books_count
              - if currently_admin?
                .label.label-default[ data-toggle="tooltip" data-placement="right" title="Digesting knowledge" ]
                  = @unpublished_books_count
              .clear-both
          li
            = link_to resume_path do
              .verb
                = @verbs["pages"]
                '
              .clear-both

      li.disabled= link_to "" do
        | that?"

app/views/layouts/_navbar_breadcrumbs.html.slim
.affixable-wrapper
  nav#navbar.navbar.navbar-default.affixable[ role="navigation" ]

    ul#social-icons.nav.navbar-right
      li= link_to "https://www.linkedin.com/in/jeehooahn" do
        = image_tag "linkedin.png"
      li= link_to "https://github.com/ahnbizcad/" do
        = image_tag "github.png"

    .bs-js-navbar-scrollspy
      ul.nav.navbar-nav
        li= link_to "#works" do 
          | Works
        li= link_to "#blog" do 
          | Blog
        li= link_to "#bookshelf" do 
          | Bookshelf
        li= link_to "#about" do
          | About

    ul.nav.navbar-nav
      li= link_to "https://www.linkedin.com/in/jeehooahn" do
        | Connect

app/views/layouts/_navbar_scrollspy.html.slim
#navbar-affixable-wrapper
  nav#navbar.navbar.navbar-default.affixable[ role="navigation" ]

    .scrollspy
      ul.nav.navbar-nav
        li= link_to "#skills" do 
          | Skills
        li= link_to "#works" do 
          | Works
        li= link_to "#bookshelf" do 
          | Bookshelf
        li= link_to "#blog" do 
          | Blog
        li= link_to "#about" do
          | About

    ul#social-icons.nav.navbar-nav
      li= link_to "https://www.linkedin.com/in/jeehooahn" do
        = image_tag "social_icons/linkedin.png"
      li= link_to "https://github.com/ahnbizcad/" do
        = image_tag "social_icons/github.png"
      li[ data-toggle="tooltip" data-placement="bottom", title="ahnjeehoo@gmail.com" ]
        = link_to "mailto:ahnjeehoo@gmail.com" do
          = image_tag "social_icons/email.svg"

#navbar-shim

app/views/layouts/_session.html.slim
#session
  .container-fluid
    .row
      .col-xs-12
        ul.nav.navbar-nav.navbar-right
          - if user_signed_in?
            li= link_to current_user.email, edit_user_registration_path
            li= link_to "Log Out", destroy_user_session_path, method: :delete
          - else
            li= link_to "Log In", new_user_session_path

app/views/layouts/_sidebar.html.slim
aside#sidebar
  .container-fluid

app/views/layouts/_spacer.html.slim
.spacer
  

app/views/layouts/application.html.slim
doctype html
html
  head
    title Jeehoo Ahn
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    | <script src="https://cdnjs.cloudflare.com/ajax/libs/prefixfree/1.0.7/prefixfree.min.js" type="application/javascript"></script>
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

    / highlight.js
    / stylesheets http://cdnjs.com/libraries/highlight.js/
    | <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/8.4/styles/monokai.min.css">
    | <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/8.4/highlight.min.js"></script>


    meta name="viewport" content="initial-scale=1.0"
  
  body[ data-spy="scroll" data-target="#navbar" data-offset="50"]
    main
      #alerts
        - flash.each do |k,v|
          div[class="alert alert-#{FlashMapper.for_bootstrap(k)} alert-dismissable" role="alert"]
            button[type="button" class="close" data-dismiss="alert" aria-label="Close"]
              span[ aria-hidden="true"]
                | &times;
            
            strong 
              = FlashMapper.for_display(k).capitalize
            ' :
            = v
      
      == yield

    - if currently_admin?
      == render partial: "layouts/session"

  = javascript_include_tag 'application_footer', 'data-turbolinks-track' => true